services:
  traccar:
    image: traccar/traccar:latest
    container_name: traccar
    restart: unless-stopped
    volumes:
      - traccar-data:/opt/traccar/data
    labels:
      - traefik.enable=true
      - traefik.docker.network=entry


      # Router
      - traefik.http.routers.traccar.rule=Host(`traccar.example.com`)
      - traefik.http.routers.traccar.entrypoints=websecure
      - traefik.http.routers.traccar.tls.certresolver=myresolver

      - traefik.http.routers.traccar.middlewares=security@docker,anubis@docker


      # Service
      - traefik.http.services.traccar.loadbalancer.server.port=8082

    networks:
      - entry

volumes:
  traccar-data: