services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    volumes:
      - ./actual/data:/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.actual-server.rule=Host(`{INSERT_URL}`)"
      - "traefik.http.routers.actual-server.entrypoints=websecure"
      - "traefik.http.routers.actual-server.tls.certresolver=myresolver"
      - "traefik.http.services.actual-server.loadbalancer.server.port=5006"
    networks:
      - entry